openapi: 3.1.0
info:
  title: Netflix Clone API Project
  description: Netflix Clone API Project
paths:
  /my-token/{email}/{token}:
    get:
      summary: Get Favorite Movie User
      parameters:
        - in: path
          name: email
          required: true
          schema:
            type: string
        - in: path
          name: token
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success Getting Favorite Movies
        401:
          description: Unauthorized
  /my-movies:
    post:
      summary: Saving User Favorite Movies To Database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: firdiaudi@gmail.com
                token:
                  type: string
                  example: 123456789
                data:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 101
                    title:
                      type: string
                      example: The Shawshank Redemption
                    genre:
                      type: string
                      example: Drama
                    year:
                      type: integer
                      example: 1994
      responses:
        201:
          description: Add Favorite Movie Success
        401:
          description: Failed Getting Favorite Movies, Unauthorized
